### PR TITLE
Mount COS_PERSISTENT in cos-deploy

### LINKED ISSUE #510: Failure in creating AWS images
Seems that cos-deploy is not mounting the persistent partition, so it tries to consume `/` instead of `COS_PERSISTENT` as actually was meant to be.

**Logs**
```     amazon-ebs.cos:  Size: 195.7KiB
    amazon-ebs.cos: \   Repository cOS revision: 36 - 2021-08-11 1824 +0000 UTC
    amazon-ebs.cos: \  Repository: cos Priority: 1 Type: docker
    amazon-ebs.cos:  Packages that are going to be inst<sensitive>ed in the system:
    amazon-ebs.cos:   cos-system-0.6.3+4 (cos)
    amazon-ebs.cos: |  Downloading image quay.io/costoolkit/releases-green:cos-system-0.6.3-4
    amazon-ebs.cos: |  failed downloading image quay.io/costoolkit/releases-green:cos-system-0.6.3-4: failed listing images: mount c<sensitive>back failed on /usr/local/.cos-upgrade/tmp/upgrade/containerd-mount455333309: write /usr/local/.cos-upgrade/tmp/upgrade/containerd-mount455333309/boot/System.map-5.3.18-59.16-default: no space left on device
==> amazon-ebs.cos: panic: runtime error: invalid memory address or nil pointer dereference
==> amazon-ebs.cos: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x192df52]
==> amazon-ebs.cos:
==> amazon-ebs.cos: goroutine 268 [running]:
==> amazon-ebs.cos: github.com/mudler/luet/pkg/compiler/types/artifact.(*Checksums).generateSum(0xc000027cf0, 0x0, 0x20f1ff8, 0xc0004b7d80, 0x1e1510d, 0x6, 0x0, 0x0)
==> amazon-ebs.cos: 	/luetbuild/go/src/github.com/mudler/luet/pkg/compiler/types/artifact/checksum.go:65 +0x52
==> amazon-ebs.cos: github.com/mudler/luet/pkg/compiler/types/artifact.(*Checksums).generateSHA256(0xc000027cf0, 0x0, 0xc0004d26c0, 0xc00070cd18)
==> amazon-ebs.cos: 	/luetbuild/go/src/github.com/mudler/luet/pkg/compiler/types/artifact/checksum.go:60 +0x88
==> amazon-ebs.cos: github.com/mudler/luet/pkg/compiler/types/artifact.(*Checksums).Generate(...)
==> amazon-ebs.cos: 	/luetbuild/go/src/github.com/mudler/luet/pkg/compiler/types/artifact/checksum.go:47
==> amazon-ebs.cos: github.com/mudler/luet/pkg/compiler/types/artifact.(*PackageArtifact).Verify(0x0, 0xc00011f5f0, 0x0)
==> amazon-ebs.cos: 	/luetbuild/go/src/github.com/mudler/luet/pkg/compiler/types/artifact/artifact.go:93 +0xb1
==> amazon-ebs.cos: github.com/mudler/luet/pkg/inst<sensitive>er.(*LuetInst<sensitive>er).downloadPackage(0xc0004640e0, 0x2116880, 0xc001959180, 0xc00011f5f0, 0xc0000b0d20, 0x2, 0x4ba065, 0x101000001b9d540)
==> amazon-ebs.cos: 	/luetbuild/go/src/github.com/mudler/luet/pkg/inst<sensitive>er/inst<sensitive>er.go:874 +0x76
==> amazon-ebs.cos: github.com/mudler/luet/pkg/inst<sensitive>er.(*LuetInst<sensitive>er).downloadWorker(0xc0004640e0, 0x1, 0xc0018e7960, 0xc0011aad80, 0x0, 0x0)
==> amazon-ebs.cos: 	/luetbuild/go/src/github.com/mudler/luet/pkg/inst<sensitive>er/inst<sensitive>er.go:908 +0x1ec
==> amazon-ebs.cos: created by github.com/mudler/luet/pkg/inst<sensitive>er.(*LuetInst<sensitive>er).download
==> amazon-ebs.cos: 	/luetbuild/go/src/github.com/mudler/luet/pkg/inst<sensitive>er/inst<sensitive>er.go:581 +0xcd
    amazon-ebs.cos: 
==> amazon-ebs.cos: Provisioning step had errors: Running the cleanup provisioner, if present...
==> amazon-ebs.cos: Terminating the source AWS instance...
==> amazon-ebs.cos: Cleaning up any extra volumes...
==> amazon-ebs.cos: Deleting temporary security group...
Build 'amazon-ebs.cos' errored after 3 minutes 27 seconds: Script exited with non-zero exit status: 2.Allowed exit codes are: [0]

==> Wait completed after 3 minutes 27 seconds
```

**Additional context**
https://github.com/rancher-sandbox/cOS-toolkit/actions/runs/1120583622

### PR DESCRIPTION
**Pull request by mudlers**
Closes #510 

Signed-off-by: Ettore Di Giacinto <edigiacinto@suse.com>

### CODE REVIEW

File: packages/installer/deploy.sh [hunk 1]
```diff
@@ -89,6 +93,8 @@ mount_image() {
         mount_state
     fi
 
+    is_mounted /usr/local || mount ${PERSISTENT} /usr/local
```
Comment (Itxaka) [inline packages/installer/deploy.sh:96]: upgrade script should also do this?

Comment (mudlers) [reply packages/installer/deploy.sh:96]: cos-upgrade is running from a system which has the partitions already in place, so `/usr/local` should be already mounted by dracut on boot

File: packages/installer/deploy.sh [hunk 2]
```diff
@@ -89,6 +93,8 @@ mount_image() {
...
+
```
Comment (Itxaka) [inline packages/installer/deploy.sh:97]: should we umount this on `clean2` just in case?

**Comment by Itxaka** [comment]
manually tested and it works as expected where the master script failed. nice!

File: packages/installer/deploy.sh (hunk 2 above)
Comment (mudlers) [reply packages/installer/deploy.sh:97]: good question :thinking: It should not do any harm... on the other hand it might be helpful for the hooks if they have to do something in the COS_PERSISTENT partition
